# WARNING: Do not commit real secrets to a public git repo.
# For production use Sealed Secrets or External Secrets Operator.
apiVersion: v1
kind: Secret
metadata:
  name: legalops-secrets
  namespace: legalops
type: Opaque
data:
  DB_PASSWORD: TGVnYWxvcHNAMTIz
  SARVAM_API_KEY: REPLACE_WITH_BASE64
  KEYCLOAK_ADMIN_PASSWORD: S2V5Y2xvYWtAMTIzNA==
